# Generated by Django 4.2.3 on 2023-07-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=50)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('meta_score', models.CharField(max_length=10)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('imdb_votes', models.CharField(max_length=50)),
                ('imdb_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.CharField(max_length=50)),
                ('box_office', models.CharField(max_length=50)),
                ('production', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
    ]
