# Generated by Django 4.2.3 on 2023-07-27 07:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
