# Generated by Django 4.2.3 on 2023-07-27 07:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0002_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=500),
        ),
    ]
